### ISSUE TITLE
Speed / Strafe False Flag

### ISSUE THREAD

**Issue by coolpvpv1** [HawkAnticheat/Hawk#28] opened 2019-11-07 05:00 UTC
if you just sprint to a ladder to try and climb it you false speed and strafe video and the mc version is 1.8.8 https://streamable.com/h1co4

**Comment by Islandscout** [comment] 2019-11-07 05:58
I am unable to reproduce this using the default configuration (Strafe is disabled by default). However, this is a known issue in Strafe and is probably one of the last issues that need to be fixed before it is finally enabled by default. https://github.com/HawkAnticheat/Hawk/blob/master/src/me/islandscout/hawk/check/movement/position/Strafe.java#L66

**Comment by Islandscout** [comment] 2020-07-14 23:45
Fixed in latest commit.

**Closed by Islandscout** 2020-07-14 23:45 UTC
Labels: in-progress, more information needed
